# Arun Agarwal, tuk82261, Assignment 3 - Multithreaded Echo Server, makefile

all: echoServer
CC = gcc
WFLAGS = -Wall -Werror

echoServer: echoServer.c
	$(CC) -o echoServer echoServer.c -lpthread -ggdb $(WFLAGS)

# server: providedEchoProgram.c //for testing the initial code
# 	$(CC) providedEchoProgram.c -o server $(WFLAGS)