# Arun Agarwal, tuk82261, Assignment 4 -Signaling, makefile

all: signal
CC = g++
WFLAGS = -Wall -Werror

signal: ThreadSignaling.cpp
	$(CC) -o signal ThreadSignaling.cpp -pthread $(WFLAGS)

# signal: ProcSignaling.cpp
# 	$(CC) -o signal ProcSignaling.cpp -pthread $(WFLAGS)